mkdir weight
mkdir weight/res14
mkdir weight/res16

wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-j2lxcITUSIaBgKiYfmEuK_n_BORjcJN' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1-j2lxcITUSIaBgKiYfmEuK_n_BORjcJN" -O weight/res14/bert-res14.pth && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-AiDE4dUg9Ocr6aTDHrKdzHhgCE8W0Md' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1-AiDE4dUg9Ocr6aTDHrKdzHhgCE8W0Md" -O weight/res14/meta-res14-blending-mlp.pth && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-Yb5O6SnmNxxqUEJXaqGJo_gmKWBeqqH' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1-Yb5O6SnmNxxqUEJXaqGJo_gmKWBeqqH" -O weight/res14/roberta-res14.pth && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=14uKsDxWof5Z4fliNhpf34a76aQKnSlHU' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=14uKsDxWof5Z4fliNhpf34a76aQKnSlHU" -O weight/res14/xlmr-res14.pth && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1wbe9mksL7-fFqmdFyW0TOKVA7PUJbv5D' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1wbe9mksL7-fFqmdFyW0TOKVA7PUJbv5D" -O weight/res14/xlnet-res14.pth && rm -rf /tmp/cookies.txt

wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-ubfhtLw6NALGSxzbrMO74GdaeXZlO4Z' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1-ubfhtLw6NALGSxzbrMO74GdaeXZlO4Z" -O weight/res16/bert-res16.pth && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-QV_r3Aygft2BlX75LB3MOuNk9parghy' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1-QV_r3Aygft2BlX75LB3MOuNk9parghy" -O weight/res16/meta-res16-blending-mlp.pth && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-gSriHGICjnT7gETcfa7xtfwDqMep_mz' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1-gSriHGICjnT7gETcfa7xtfwDqMep_mz" -O weight/res16/roberta-res16.pth && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-BruVhjr5R6HG7hEt_gbEYmL5mCcUmB1' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1-BruVhjr5R6HG7hEt_gbEYmL5mCcUmB1" -O weight/res16/xlmr-res16.pth && rm -rf /tmp/cookies.txt
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1-CF5VzaIPBsdO-je9Vz6EJhV_EgXtdcm' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1-CF5VzaIPBsdO-je9Vz6EJhV_EgXtdcm" -O weight/res16/xlnet-res16.pth && rm -rf /tmp/cookies.txt
